#!/bin/ksh
#*************************************************************************/
#* Script Name   : archive_files.sh			       	   *
#* Creation Date : 08/09/2016                                            *
#* Created By    : Marvin Simon                                          *
#*                                                                       *
#* Serial Number :                                                       * 
#*                                                                       *
#* Description   : Script to archive files. Three parameters are the     *
#*                 input directory, file destination and pay period.     *
#*                                                                       *
#* Input Parms:   File Name                                              *
#* Called By:     Manually;cron                                          *
#*                                                                       *
#*                                                                       *
#* Modifications:                                                        *
#*                                                                       *
#* -------- -------- --------------------------------------------------- *
#*************************************************************************/

if [ $# -ne 3 ] || [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Usage: archive_files.sh <inputdir> <filedest> <pay_period>" >&2
    exit 1
fi

inputdir=$1

filedest=$2

pay_period=$3

if [ ! -d "$filedest" ]; then
    echo "Destination directory not found: $filedest" >&2
    exit 1
fi

cd "$inputdir" || { echo "Cannot cd to input directory: $inputdir" >&2; exit 1; }

for file in *
do

    [ -f "$file" ] || continue

    fileprefix=$(basename "$file" .txt)

    mv -- "${file}" "${filedest}"/"${fileprefix}"_P"${pay_period}".txt || exit 1

done
