#!/bin/ksh
#*************************************************************************/
#* Script Name   : remove_file.sh			       	          *
#* Creation Date : 08/09/2016                                            *
#* Created By    : Marvin Simon                                          *
#*                                                                       *
#* Serial Number :                                                       * 
#*                                                                       *
#* Description   : Script to remove file. Two parameters are the         *
#*                 input directory and file name.                        *
#*                                                                       *
#* Input Parms:   File Name                                              *
#* Called By:     Manually;cron                                          *
#*                                                                       *
#*                                                                       *
#* Modifications:                                                        *
#*                                                                       *
#* -------- -------- --------------------------------------------------- *
#*************************************************************************/

if [ $# -ne 2 ] || [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: remove_file.sh <inputdir> <filename>" >&2
    exit 1
fi

inputdir=$1

filename=$2

cd "$inputdir" || { echo "Cannot cd to input directory: $inputdir" >&2; exit 1; }

if [ -f "$filename" ]; then

   rm -- "$filename"

fi
